// Code generated by protoc-gen-go.
// source: contact.proto
// DO NOT EDIT!

/*
Package ricochet is a generated protocol buffer package.

It is generated from these files:
	contact.proto
	conversation.proto
	core.proto
	identity.proto
	network.proto

It has these top-level messages:
	Contact
	ContactRequest
	MonitorContactsRequest
	ContactEvent
	AddContactReply
	DeleteContactRequest
	DeleteContactReply
	RejectInboundRequestReply
	ConversationEvent
	MonitorConversationsRequest
	Entity
	Message
	MarkConversationReadRequest
	Reply
	ServerStatusRequest
	ServerStatusReply
	Identity
	IdentityRequest
	MonitorNetworkRequest
	TorProcessStatus
	TorControlStatus
	TorConnectionStatus
	NetworkStatus
	StartNetworkRequest
	StopNetworkRequest
*/
package ricochet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Contact_Status int32

const (
	Contact_UNKNOWN  Contact_Status = 0
	Contact_OFFLINE  Contact_Status = 1
	Contact_ONLINE   Contact_Status = 2
	Contact_REQUEST  Contact_Status = 3
	Contact_REJECTED Contact_Status = 4
)

var Contact_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "OFFLINE",
	2: "ONLINE",
	3: "REQUEST",
	4: "REJECTED",
}
var Contact_Status_value = map[string]int32{
	"UNKNOWN":  0,
	"OFFLINE":  1,
	"ONLINE":   2,
	"REQUEST":  3,
	"REJECTED": 4,
}

func (x Contact_Status) String() string {
	return proto.EnumName(Contact_Status_name, int32(x))
}
func (Contact_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ContactRequest_Direction int32

const (
	ContactRequest_INBOUND  ContactRequest_Direction = 0
	ContactRequest_OUTBOUND ContactRequest_Direction = 1
)

var ContactRequest_Direction_name = map[int32]string{
	0: "INBOUND",
	1: "OUTBOUND",
}
var ContactRequest_Direction_value = map[string]int32{
	"INBOUND":  0,
	"OUTBOUND": 1,
}

func (x ContactRequest_Direction) String() string {
	return proto.EnumName(ContactRequest_Direction_name, int32(x))
}
func (ContactRequest_Direction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type ContactEvent_Type int32

const (
	ContactEvent_NULL     ContactEvent_Type = 0
	ContactEvent_POPULATE ContactEvent_Type = 1
	ContactEvent_ADD      ContactEvent_Type = 2
	ContactEvent_UPDATE   ContactEvent_Type = 3
	ContactEvent_DELETE   ContactEvent_Type = 4
)

var ContactEvent_Type_name = map[int32]string{
	0: "NULL",
	1: "POPULATE",
	2: "ADD",
	3: "UPDATE",
	4: "DELETE",
}
var ContactEvent_Type_value = map[string]int32{
	"NULL":     0,
	"POPULATE": 1,
	"ADD":      2,
	"UPDATE":   3,
	"DELETE":   4,
}

func (x ContactEvent_Type) String() string {
	return proto.EnumName(ContactEvent_Type_name, int32(x))
}
func (ContactEvent_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type Contact struct {
	Id            int32           `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Address       string          `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Nickname      string          `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	WhenCreated   string          `protobuf:"bytes,4,opt,name=whenCreated" json:"whenCreated,omitempty"`
	LastConnected string          `protobuf:"bytes,5,opt,name=lastConnected" json:"lastConnected,omitempty"`
	Request       *ContactRequest `protobuf:"bytes,6,opt,name=request" json:"request,omitempty"`
	Status        Contact_Status  `protobuf:"varint,10,opt,name=status,enum=ricochet.Contact_Status" json:"status,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Contact) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contact) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Contact) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Contact) GetWhenCreated() string {
	if m != nil {
		return m.WhenCreated
	}
	return ""
}

func (m *Contact) GetLastConnected() string {
	if m != nil {
		return m.LastConnected
	}
	return ""
}

func (m *Contact) GetRequest() *ContactRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Contact) GetStatus() Contact_Status {
	if m != nil {
		return m.Status
	}
	return Contact_UNKNOWN
}

type ContactRequest struct {
	Direction    ContactRequest_Direction `protobuf:"varint,1,opt,name=direction,enum=ricochet.ContactRequest_Direction" json:"direction,omitempty"`
	Address      string                   `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Nickname     string                   `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	Text         string                   `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
	FromNickname string                   `protobuf:"bytes,5,opt,name=fromNickname" json:"fromNickname,omitempty"`
}

func (m *ContactRequest) Reset()                    { *m = ContactRequest{} }
func (m *ContactRequest) String() string            { return proto.CompactTextString(m) }
func (*ContactRequest) ProtoMessage()               {}
func (*ContactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ContactRequest) GetDirection() ContactRequest_Direction {
	if m != nil {
		return m.Direction
	}
	return ContactRequest_INBOUND
}

func (m *ContactRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ContactRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *ContactRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ContactRequest) GetFromNickname() string {
	if m != nil {
		return m.FromNickname
	}
	return ""
}

type MonitorContactsRequest struct {
}

func (m *MonitorContactsRequest) Reset()                    { *m = MonitorContactsRequest{} }
func (m *MonitorContactsRequest) String() string            { return proto.CompactTextString(m) }
func (*MonitorContactsRequest) ProtoMessage()               {}
func (*MonitorContactsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ContactEvent struct {
	Type ContactEvent_Type `protobuf:"varint,1,opt,name=type,enum=ricochet.ContactEvent_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Subject:
	//	*ContactEvent_Contact
	//	*ContactEvent_Request
	Subject isContactEvent_Subject `protobuf_oneof:"subject"`
}

func (m *ContactEvent) Reset()                    { *m = ContactEvent{} }
func (m *ContactEvent) String() string            { return proto.CompactTextString(m) }
func (*ContactEvent) ProtoMessage()               {}
func (*ContactEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isContactEvent_Subject interface {
	isContactEvent_Subject()
}

type ContactEvent_Contact struct {
	Contact *Contact `protobuf:"bytes,2,opt,name=contact,oneof"`
}
type ContactEvent_Request struct {
	Request *ContactRequest `protobuf:"bytes,3,opt,name=request,oneof"`
}

func (*ContactEvent_Contact) isContactEvent_Subject() {}
func (*ContactEvent_Request) isContactEvent_Subject() {}

func (m *ContactEvent) GetSubject() isContactEvent_Subject {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *ContactEvent) GetType() ContactEvent_Type {
	if m != nil {
		return m.Type
	}
	return ContactEvent_NULL
}

func (m *ContactEvent) GetContact() *Contact {
	if x, ok := m.GetSubject().(*ContactEvent_Contact); ok {
		return x.Contact
	}
	return nil
}

func (m *ContactEvent) GetRequest() *ContactRequest {
	if x, ok := m.GetSubject().(*ContactEvent_Request); ok {
		return x.Request
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ContactEvent) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ContactEvent_OneofMarshaler, _ContactEvent_OneofUnmarshaler, _ContactEvent_OneofSizer, []interface{}{
		(*ContactEvent_Contact)(nil),
		(*ContactEvent_Request)(nil),
	}
}

func _ContactEvent_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ContactEvent)
	// subject
	switch x := m.Subject.(type) {
	case *ContactEvent_Contact:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Contact); err != nil {
			return err
		}
	case *ContactEvent_Request:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Request); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ContactEvent.Subject has unexpected type %T", x)
	}
	return nil
}

func _ContactEvent_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ContactEvent)
	switch tag {
	case 2: // subject.contact
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Contact)
		err := b.DecodeMessage(msg)
		m.Subject = &ContactEvent_Contact{msg}
		return true, err
	case 3: // subject.request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ContactRequest)
		err := b.DecodeMessage(msg)
		m.Subject = &ContactEvent_Request{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ContactEvent_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ContactEvent)
	// subject
	switch x := m.Subject.(type) {
	case *ContactEvent_Contact:
		s := proto.Size(x.Contact)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ContactEvent_Request:
		s := proto.Size(x.Request)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type AddContactReply struct {
}

func (m *AddContactReply) Reset()                    { *m = AddContactReply{} }
func (m *AddContactReply) String() string            { return proto.CompactTextString(m) }
func (*AddContactReply) ProtoMessage()               {}
func (*AddContactReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeleteContactRequest struct {
	Id      int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *DeleteContactRequest) Reset()                    { *m = DeleteContactRequest{} }
func (m *DeleteContactRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteContactRequest) ProtoMessage()               {}
func (*DeleteContactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteContactRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteContactRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteContactReply struct {
}

func (m *DeleteContactReply) Reset()                    { *m = DeleteContactReply{} }
func (m *DeleteContactReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteContactReply) ProtoMessage()               {}
func (*DeleteContactReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type RejectInboundRequestReply struct {
}

func (m *RejectInboundRequestReply) Reset()                    { *m = RejectInboundRequestReply{} }
func (m *RejectInboundRequestReply) String() string            { return proto.CompactTextString(m) }
func (*RejectInboundRequestReply) ProtoMessage()               {}
func (*RejectInboundRequestReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*Contact)(nil), "ricochet.Contact")
	proto.RegisterType((*ContactRequest)(nil), "ricochet.ContactRequest")
	proto.RegisterType((*MonitorContactsRequest)(nil), "ricochet.MonitorContactsRequest")
	proto.RegisterType((*ContactEvent)(nil), "ricochet.ContactEvent")
	proto.RegisterType((*AddContactReply)(nil), "ricochet.AddContactReply")
	proto.RegisterType((*DeleteContactRequest)(nil), "ricochet.DeleteContactRequest")
	proto.RegisterType((*DeleteContactReply)(nil), "ricochet.DeleteContactReply")
	proto.RegisterType((*RejectInboundRequestReply)(nil), "ricochet.RejectInboundRequestReply")
	proto.RegisterEnum("ricochet.Contact_Status", Contact_Status_name, Contact_Status_value)
	proto.RegisterEnum("ricochet.ContactRequest_Direction", ContactRequest_Direction_name, ContactRequest_Direction_value)
	proto.RegisterEnum("ricochet.ContactEvent_Type", ContactEvent_Type_name, ContactEvent_Type_value)
}

func init() { proto.RegisterFile("contact.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0x6e, 0xd2, 0xac, 0x69, 0xaf, 0x5d, 0xc9, 0xac, 0x09, 0x05, 0xf6, 0x52, 0x59, 0x08, 0xf5,
	0x85, 0x80, 0x0a, 0xef, 0xac, 0x6b, 0x32, 0x51, 0x08, 0x49, 0xf1, 0x12, 0xf1, 0x9c, 0x26, 0x46,
	0x0b, 0x74, 0x76, 0x49, 0x5c, 0xa0, 0xff, 0x90, 0x9f, 0xc2, 0x23, 0x3f, 0x01, 0xd9, 0x49, 0x3a,
	0xba, 0x01, 0x42, 0x7b, 0xf3, 0x7d, 0xdf, 0x77, 0xf6, 0x7d, 0xbe, 0x3b, 0x38, 0x4c, 0x39, 0x13,
	0x49, 0x2a, 0x9c, 0x75, 0xc1, 0x05, 0x47, 0xdd, 0x22, 0x4f, 0x79, 0x7a, 0x49, 0x05, 0xfe, 0xae,
	0x83, 0x39, 0xab, 0x38, 0x34, 0x04, 0x3d, 0xcf, 0x6c, 0x6d, 0xa4, 0x8d, 0x0f, 0x88, 0x9e, 0x67,
	0xc8, 0x06, 0x33, 0xc9, 0xb2, 0x82, 0x96, 0xa5, 0xad, 0x8f, 0xb4, 0x71, 0x8f, 0x34, 0x21, 0x7a,
	0x08, 0x5d, 0x96, 0xa7, 0x9f, 0x58, 0x72, 0x45, 0xed, 0xb6, 0xa2, 0x76, 0x31, 0x1a, 0x41, 0xff,
	0xeb, 0x25, 0x65, 0xb3, 0x82, 0x26, 0x82, 0x66, 0xb6, 0xa1, 0xe8, 0xdf, 0x21, 0xf4, 0x08, 0x0e,
	0x57, 0x49, 0x29, 0x66, 0x9c, 0x31, 0x9a, 0x4a, 0xcd, 0x81, 0xd2, 0xec, 0x83, 0x68, 0x02, 0x66,
	0x41, 0x3f, 0x6f, 0x68, 0x29, 0xec, 0xce, 0x48, 0x1b, 0xf7, 0x27, 0xb6, 0xd3, 0x54, 0xed, 0xd4,
	0x15, 0x93, 0x8a, 0x27, 0x8d, 0x10, 0x3d, 0x83, 0x4e, 0x29, 0x12, 0xb1, 0x29, 0x6d, 0x18, 0x69,
	0xe3, 0xe1, 0x1f, 0x52, 0x9c, 0x0b, 0xc5, 0x93, 0x5a, 0x87, 0xe7, 0xd0, 0xa9, 0x10, 0xd4, 0x07,
	0x33, 0x0e, 0xde, 0x04, 0xe1, 0xfb, 0xc0, 0x6a, 0xc9, 0x20, 0x3c, 0x3f, 0xf7, 0xe7, 0x81, 0x67,
	0x69, 0x08, 0xa0, 0x13, 0x06, 0xea, 0xac, 0x4b, 0x82, 0x78, 0xef, 0x62, 0xef, 0x22, 0xb2, 0xda,
	0x68, 0x00, 0x5d, 0xe2, 0xbd, 0xf6, 0x66, 0x91, 0xe7, 0x5a, 0x06, 0xfe, 0xa1, 0xc1, 0x70, 0xbf,
	0x30, 0x74, 0x0a, 0xbd, 0x2c, 0x2f, 0x68, 0x2a, 0x72, 0xce, 0xd4, 0xc7, 0x0e, 0x27, 0xf8, 0x6f,
	0x2e, 0x1c, 0xb7, 0x51, 0x92, 0xeb, 0xa4, 0x3b, 0xf6, 0x00, 0x81, 0x21, 0xe8, 0x37, 0x51, 0x7f,
	0xbe, 0x3a, 0x23, 0x0c, 0x83, 0x0f, 0x05, 0xbf, 0x0a, 0x9a, 0x9c, 0xea, 0xd3, 0xf7, 0x30, 0xfc,
	0x18, 0x7a, 0xbb, 0x2a, 0xa4, 0xd5, 0x79, 0x70, 0x16, 0xc6, 0x81, 0x6b, 0xb5, 0xa4, 0xd5, 0x30,
	0x8e, 0xaa, 0x48, 0xc3, 0x36, 0xdc, 0x7f, 0xcb, 0x59, 0x2e, 0x78, 0x51, 0x7b, 0x28, 0x6b, 0x13,
	0xf8, 0xa7, 0x06, 0x83, 0x1a, 0xf3, 0xbe, 0x50, 0x26, 0xd0, 0x53, 0x30, 0xc4, 0x76, 0x4d, 0x6b,
	0xf7, 0x27, 0xb7, 0xdc, 0x2b, 0x95, 0x13, 0x6d, 0xd7, 0x94, 0x28, 0x21, 0x7a, 0x02, 0x66, 0x3d,
	0xac, 0xca, 0x71, 0x7f, 0x72, 0x74, 0x2b, 0xe7, 0x55, 0x8b, 0x34, 0x1a, 0xf4, 0xe2, 0x7a, 0x4c,
	0xda, 0xff, 0x1e, 0x13, 0x99, 0x55, 0x4b, 0xf1, 0x4b, 0x30, 0xe4, 0x93, 0xa8, 0x0b, 0x46, 0x10,
	0xfb, 0x7e, 0x65, 0x70, 0x11, 0x2e, 0x62, 0x7f, 0x1a, 0xc9, 0x96, 0x9b, 0xd0, 0x9e, 0xba, 0xae,
	0xa5, 0xcb, 0xde, 0xc7, 0x0b, 0x57, 0x82, 0x6d, 0x79, 0x76, 0x3d, 0xdf, 0x8b, 0x3c, 0xcb, 0x38,
	0xeb, 0x81, 0x59, 0x6e, 0x96, 0x1f, 0x69, 0x2a, 0xf0, 0x11, 0xdc, 0x9b, 0x66, 0xd9, 0xee, 0xad,
	0xf5, 0x6a, 0x8b, 0x4f, 0xe1, 0xd8, 0xa5, 0x2b, 0x2a, 0xe8, 0x8d, 0x79, 0xf8, 0xef, 0x0d, 0xc3,
	0xc7, 0x80, 0x6e, 0xdc, 0x20, 0xef, 0x3d, 0x81, 0x07, 0x84, 0xca, 0x47, 0xe7, 0x6c, 0xc9, 0x37,
	0x2c, 0x6b, 0x16, 0x40, 0x92, 0xcb, 0x8e, 0xda, 0xed, 0xe7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x94, 0xcf, 0x1c, 0xce, 0xec, 0x03, 0x00, 0x00,
}
