// Code generated by protoc-gen-go.
// source: network.proto
// DO NOT EDIT!

package ricochet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TorProcessStatus_Status int32

const (
	TorProcessStatus_DISABLED TorProcessStatus_Status = 0
	TorProcessStatus_STOPPED  TorProcessStatus_Status = 1
	TorProcessStatus_STARTING TorProcessStatus_Status = 2
	TorProcessStatus_RUNNING  TorProcessStatus_Status = 3
)

var TorProcessStatus_Status_name = map[int32]string{
	0: "DISABLED",
	1: "STOPPED",
	2: "STARTING",
	3: "RUNNING",
}
var TorProcessStatus_Status_value = map[string]int32{
	"DISABLED": 0,
	"STOPPED":  1,
	"STARTING": 2,
	"RUNNING":  3,
}

func (x TorProcessStatus_Status) String() string {
	return proto.EnumName(TorProcessStatus_Status_name, int32(x))
}
func (TorProcessStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{1, 0} }

type TorControlStatus_Status int32

const (
	TorControlStatus_STOPPED    TorControlStatus_Status = 0
	TorControlStatus_ERROR      TorControlStatus_Status = 1
	TorControlStatus_CONNECTING TorControlStatus_Status = 2
	TorControlStatus_CONNECTED  TorControlStatus_Status = 3
)

var TorControlStatus_Status_name = map[int32]string{
	0: "STOPPED",
	1: "ERROR",
	2: "CONNECTING",
	3: "CONNECTED",
}
var TorControlStatus_Status_value = map[string]int32{
	"STOPPED":    0,
	"ERROR":      1,
	"CONNECTING": 2,
	"CONNECTED":  3,
}

func (x TorControlStatus_Status) String() string {
	return proto.EnumName(TorControlStatus_Status_name, int32(x))
}
func (TorControlStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{2, 0} }

type TorConnectionStatus_Status int32

const (
	TorConnectionStatus_UNKNOWN       TorConnectionStatus_Status = 0
	TorConnectionStatus_OFFLINE       TorConnectionStatus_Status = 1
	TorConnectionStatus_BOOTSTRAPPING TorConnectionStatus_Status = 2
	TorConnectionStatus_READY         TorConnectionStatus_Status = 3
)

var TorConnectionStatus_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "OFFLINE",
	2: "BOOTSTRAPPING",
	3: "READY",
}
var TorConnectionStatus_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"OFFLINE":       1,
	"BOOTSTRAPPING": 2,
	"READY":         3,
}

func (x TorConnectionStatus_Status) String() string {
	return proto.EnumName(TorConnectionStatus_Status_name, int32(x))
}
func (TorConnectionStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{3, 0}
}

type MonitorNetworkRequest struct {
}

func (m *MonitorNetworkRequest) Reset()                    { *m = MonitorNetworkRequest{} }
func (m *MonitorNetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*MonitorNetworkRequest) ProtoMessage()               {}
func (*MonitorNetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

type TorProcessStatus struct {
	Status       TorProcessStatus_Status `protobuf:"varint,1,opt,name=status,enum=ricochet.TorProcessStatus_Status" json:"status,omitempty"`
	ErrorMessage string                  `protobuf:"bytes,2,opt,name=errorMessage" json:"errorMessage,omitempty"`
}

func (m *TorProcessStatus) Reset()                    { *m = TorProcessStatus{} }
func (m *TorProcessStatus) String() string            { return proto.CompactTextString(m) }
func (*TorProcessStatus) ProtoMessage()               {}
func (*TorProcessStatus) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *TorProcessStatus) GetStatus() TorProcessStatus_Status {
	if m != nil {
		return m.Status
	}
	return TorProcessStatus_DISABLED
}

func (m *TorProcessStatus) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type TorControlStatus struct {
	Status       TorControlStatus_Status `protobuf:"varint,1,opt,name=status,enum=ricochet.TorControlStatus_Status" json:"status,omitempty"`
	ErrorMessage string                  `protobuf:"bytes,2,opt,name=errorMessage" json:"errorMessage,omitempty"`
	TorVersion   string                  `protobuf:"bytes,10,opt,name=torVersion" json:"torVersion,omitempty"`
}

func (m *TorControlStatus) Reset()                    { *m = TorControlStatus{} }
func (m *TorControlStatus) String() string            { return proto.CompactTextString(m) }
func (*TorControlStatus) ProtoMessage()               {}
func (*TorControlStatus) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *TorControlStatus) GetStatus() TorControlStatus_Status {
	if m != nil {
		return m.Status
	}
	return TorControlStatus_STOPPED
}

func (m *TorControlStatus) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *TorControlStatus) GetTorVersion() string {
	if m != nil {
		return m.TorVersion
	}
	return ""
}

type TorConnectionStatus struct {
	Status            TorConnectionStatus_Status `protobuf:"varint,1,opt,name=status,enum=ricochet.TorConnectionStatus_Status" json:"status,omitempty"`
	BootstrapProgress string                     `protobuf:"bytes,10,opt,name=bootstrapProgress" json:"bootstrapProgress,omitempty"`
	SocksAddress      []string                   `protobuf:"bytes,11,rep,name=socksAddress" json:"socksAddress,omitempty"`
}

func (m *TorConnectionStatus) Reset()                    { *m = TorConnectionStatus{} }
func (m *TorConnectionStatus) String() string            { return proto.CompactTextString(m) }
func (*TorConnectionStatus) ProtoMessage()               {}
func (*TorConnectionStatus) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *TorConnectionStatus) GetStatus() TorConnectionStatus_Status {
	if m != nil {
		return m.Status
	}
	return TorConnectionStatus_UNKNOWN
}

func (m *TorConnectionStatus) GetBootstrapProgress() string {
	if m != nil {
		return m.BootstrapProgress
	}
	return ""
}

func (m *TorConnectionStatus) GetSocksAddress() []string {
	if m != nil {
		return m.SocksAddress
	}
	return nil
}

type NetworkStatus struct {
	Process    *TorProcessStatus    `protobuf:"bytes,1,opt,name=process" json:"process,omitempty"`
	Control    *TorControlStatus    `protobuf:"bytes,2,opt,name=control" json:"control,omitempty"`
	Connection *TorConnectionStatus `protobuf:"bytes,3,opt,name=connection" json:"connection,omitempty"`
}

func (m *NetworkStatus) Reset()                    { *m = NetworkStatus{} }
func (m *NetworkStatus) String() string            { return proto.CompactTextString(m) }
func (*NetworkStatus) ProtoMessage()               {}
func (*NetworkStatus) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *NetworkStatus) GetProcess() *TorProcessStatus {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *NetworkStatus) GetControl() *TorControlStatus {
	if m != nil {
		return m.Control
	}
	return nil
}

func (m *NetworkStatus) GetConnection() *TorConnectionStatus {
	if m != nil {
		return m.Connection
	}
	return nil
}

type StartNetworkRequest struct {
}

func (m *StartNetworkRequest) Reset()                    { *m = StartNetworkRequest{} }
func (m *StartNetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*StartNetworkRequest) ProtoMessage()               {}
func (*StartNetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

type StopNetworkRequest struct {
}

func (m *StopNetworkRequest) Reset()                    { *m = StopNetworkRequest{} }
func (m *StopNetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*StopNetworkRequest) ProtoMessage()               {}
func (*StopNetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func init() {
	proto.RegisterType((*MonitorNetworkRequest)(nil), "ricochet.MonitorNetworkRequest")
	proto.RegisterType((*TorProcessStatus)(nil), "ricochet.TorProcessStatus")
	proto.RegisterType((*TorControlStatus)(nil), "ricochet.TorControlStatus")
	proto.RegisterType((*TorConnectionStatus)(nil), "ricochet.TorConnectionStatus")
	proto.RegisterType((*NetworkStatus)(nil), "ricochet.NetworkStatus")
	proto.RegisterType((*StartNetworkRequest)(nil), "ricochet.StartNetworkRequest")
	proto.RegisterType((*StopNetworkRequest)(nil), "ricochet.StopNetworkRequest")
	proto.RegisterEnum("ricochet.TorProcessStatus_Status", TorProcessStatus_Status_name, TorProcessStatus_Status_value)
	proto.RegisterEnum("ricochet.TorControlStatus_Status", TorControlStatus_Status_name, TorControlStatus_Status_value)
	proto.RegisterEnum("ricochet.TorConnectionStatus_Status", TorConnectionStatus_Status_name, TorConnectionStatus_Status_value)
}

func init() { proto.RegisterFile("network.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xee, 0xd6, 0x6a, 0xda, 0x4c, 0x9a, 0xca, 0xdd, 0x52, 0x11, 0x21, 0x81, 0xc2, 0x8a, 0x43,
	0x0f, 0x28, 0x87, 0xc2, 0x05, 0x89, 0x3f, 0x37, 0x76, 0x51, 0x44, 0xbb, 0xb6, 0xd6, 0x2e, 0x88,
	0x63, 0xea, 0xae, 0x4a, 0x54, 0xe4, 0x09, 0xb3, 0x5b, 0xf1, 0x5c, 0x5c, 0x79, 0x0c, 0x5e, 0x82,
	0xd7, 0x40, 0xb6, 0x37, 0x91, 0x6d, 0x04, 0x42, 0x3d, 0xd9, 0x3b, 0xf3, 0x7d, 0xb3, 0xdf, 0x37,
	0x33, 0x0b, 0xc3, 0x42, 0xdb, 0x6f, 0x48, 0x37, 0x93, 0x25, 0xa1, 0x45, 0xbe, 0x43, 0x8b, 0x1c,
	0xf3, 0xcf, 0xda, 0x8a, 0xfb, 0x70, 0x78, 0x8e, 0xc5, 0xc2, 0x22, 0xc9, 0x1a, 0xa1, 0xf4, 0xd7,
	0x5b, 0x6d, 0xac, 0xf8, 0xce, 0xc0, 0xcf, 0x90, 0x12, 0xc2, 0x5c, 0x1b, 0x93, 0xda, 0xb9, 0xbd,
	0x35, 0xfc, 0x05, 0xf4, 0x4c, 0xf5, 0x37, 0x62, 0x63, 0x76, 0xb4, 0x77, 0xfc, 0x78, 0xb2, 0x2a,
	0x34, 0xe9, 0x62, 0x27, 0xf5, 0x47, 0x39, 0x02, 0x17, 0xb0, 0xab, 0x89, 0x90, 0xce, 0xb5, 0x31,
	0xf3, 0x6b, 0x3d, 0xda, 0x1c, 0xb3, 0xa3, 0xbe, 0x6a, 0xc5, 0xc4, 0x6b, 0xe8, 0xb9, 0x8b, 0x76,
	0x61, 0x27, 0x9c, 0xa5, 0xc1, 0xc9, 0x59, 0x14, 0xfa, 0x1b, 0x7c, 0x00, 0xdb, 0x69, 0x16, 0x27,
	0x49, 0x14, 0xfa, 0xac, 0x4c, 0xa5, 0x59, 0xa0, 0xb2, 0x99, 0x7c, 0xe7, 0x6f, 0x96, 0x29, 0x75,
	0x21, 0x65, 0x79, 0xf0, 0xc4, 0xcf, 0x5a, 0xf3, 0x14, 0x0b, 0x4b, 0xf8, 0xe5, 0xbf, 0x34, 0xb7,
	0xb0, 0x77, 0xd0, 0xcc, 0x1f, 0x01, 0x58, 0xa4, 0x0f, 0x9a, 0xcc, 0x02, 0x8b, 0x11, 0x54, 0x88,
	0x46, 0x44, 0xbc, 0x59, 0x7b, 0x6a, 0xb8, 0xd8, 0xe0, 0x7d, 0xd8, 0x8a, 0x94, 0x8a, 0x95, 0xcf,
	0xf8, 0x1e, 0xc0, 0x34, 0x96, 0x32, 0x9a, 0x3a, 0x4b, 0x43, 0xe8, 0xbb, 0x73, 0x14, 0xfa, 0x9e,
	0xf8, 0xc5, 0xe0, 0xa0, 0x16, 0x5a, 0xe8, 0xdc, 0x2e, 0xb0, 0x70, 0xe5, 0x5e, 0x76, 0x7c, 0x3d,
	0xe9, 0xfa, 0x6a, 0xc1, 0xbb, 0xd6, 0x9e, 0xc2, 0xfe, 0x25, 0xa2, 0x35, 0x96, 0xe6, 0xcb, 0x84,
	0xf0, 0x9a, 0xb4, 0x31, 0x4e, 0xfd, 0x9f, 0x89, 0xb2, 0x11, 0x06, 0xf3, 0x1b, 0x13, 0x5c, 0x5d,
	0x55, 0xc0, 0xc1, 0xd8, 0x2b, 0x1b, 0xd1, 0x8c, 0x89, 0xb7, 0x4d, 0xa3, 0x17, 0xf2, 0xbd, 0x8c,
	0x3f, 0xca, 0x7a, 0x76, 0xf1, 0xe9, 0xe9, 0xd9, 0x4c, 0x46, 0x3e, 0xe3, 0xfb, 0x30, 0x3c, 0x89,
	0xe3, 0x2c, 0xcd, 0x54, 0x90, 0x24, 0xb5, 0xdb, 0x3e, 0x6c, 0xa9, 0x28, 0x08, 0x3f, 0xf9, 0x9e,
	0xf8, 0xc1, 0x60, 0xe8, 0xb6, 0xd0, 0x55, 0x7a, 0x0e, 0xdb, 0xcb, 0x7a, 0xa9, 0x2a, 0x93, 0x83,
	0xe3, 0x07, 0x7f, 0x5f, 0x38, 0xb5, 0x82, 0x96, 0xac, 0xbc, 0x1e, 0x6b, 0x35, 0xb1, 0x2e, 0xab,
	0x35, 0x72, 0xb5, 0x82, 0xf2, 0x57, 0x00, 0xf9, 0xba, 0x69, 0x23, 0xaf, 0x22, 0x3e, 0xfc, 0x67,
	0x4f, 0x55, 0x83, 0x20, 0x0e, 0xe1, 0x20, 0xb5, 0x73, 0xb2, 0x9d, 0x67, 0x74, 0x0f, 0x78, 0x6a,
	0x71, 0xd9, 0x8e, 0x5e, 0xf6, 0xaa, 0x67, 0xf8, 0xec, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78,
	0x89, 0xf8, 0x34, 0x97, 0x03, 0x00, 0x00,
}
